Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,129 @@
-# This is a basic workflow to help you get started with Actions
+name: new eee
+on: [pull_request]
 
-name: CI
 
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+env:
+  GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+permissions:
+  id-token: write
+  contents: read
+  checks: write
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  # unit-test:
+  #   name: Unit Test
+  #   # https://github.com/actions/runner/issues/774
+  #   if: "!contains(github.event.head_commit.message, 'skip ci')"
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: ${{ fromJSON(vars.WORKFLOW_TIMEOUT_IN_MINUTES) }}
+
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: 'Install dependencies'
+  #       uses: ./.github/actions/dependencies
+  #       with:
+  #         node-version: '18.x'
+  #     # - run: npm run lint
+  #     # - run: npm run test
+
+  terraform-deploy:
+    name: AWS-Services Deploy
+    # needs: [unit-test]
     runs-on: ubuntu-latest
+    timeout-minutes: ${{ fromJSON(vars.WORKFLOW_TIMEOUT_IN_MINUTES) }}
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
+      - name: 'Assume AWS role'
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - name: 'Deploy the stack'
+        uses: ./.github/actions/terraform
+        with:
+          workspace: pr-1
+          action: apply
+          lambda-version: ${{ github.sha }}
+          working-directory: ./terraform
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+  node-deploy:
+    name: Node Deploy
+    runs-on: ubuntu-latest
+    timeout-minutes: ${{ fromJSON(vars.WORKFLOW_TIMEOUT_IN_MINUTES) }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - name: 'Install dependencies'
+        uses: ./.github/actions/dependencies
+        with:
+          node-version: '18.x'
+
+      - name: Create App Directory on EC2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            mkdir -p /home/ubuntu/app
+            chown -R ubuntu:ubuntu /home/ubuntu/app
+            chmod -R 755 /home/ubuntu/app
+            
+      - name: Deploy to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: "."  # Change this if your application files are in a different directory
+          target: "/home/ubuntu/app"  # Change this to the destination directory on your EC2 instance
+          overwrite: true
+
+      - name: SSH into EC2 and Restart Application
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd /home/ubuntu/app
+            pm2 restart index.js 
+
+  # int-test:
+  #   name: Test Deployed Lambda
+  #   needs: [deploy]
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: ${{ fromJSON(vars.WORKFLOW_TIMEOUT_IN_MINUTES) }}
+
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: 'Install dependencies'
+  #       uses: alamy-ops/github-actions/actions/install-node-dependencies@main
+  #       with:
+  #         node-version: '18.x'
+
+  #     - name: 'Assume AWS role'
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-region: eu-west-1
+  #         role-to-assume: arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
+
+  #     - name: Run Tests
+  #       run: npm run test:int:ci
+  #       env:
+  #         LAMBDA_ARN: test-terraform-github-deploy-pr-${{ github.event.pull_request.number }}
+  #         TEST_ENV: development
+
+  #     - name: Publish test report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure()
+  #       with:
+  #         name: Int test Report
+  #         path: reports/junit-int.xml
+  #         reporter: jest-junit
+
+ 
